#!/usr/bin/env python 
# -*- coding:utf-8 -*-

"公共"
chat_head_back="com.immuxin.muxin:id/chat_head_back"

"首页"
message ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.support.v4.view.ViewPager/android.widget.LinearLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout[1]"
muxin="com.immuxin.muxin:id/ll_chat"
etInput="com.immuxin.muxin:id/etInput"
ivSendMsg="com.immuxin.muxin:id/ivSendMsg"
custom_edit_query="com.immuxin.muxin:id/custom_edit_query"
search_activity_search_right_text="com.immuxin.muxin:id/search_activity_search_right_text"


"联系人"
ll_contacts="com.immuxin.muxin:id/ll_contacts"
layoutSendMsg="com.immuxin.muxin:id/layoutSendMsg"
contacts="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.support.v4.view.ViewPager/android.widget.LinearLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.RelativeLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout"
contacts2="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.support.v4.view.ViewPager/android.widget.LinearLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.RelativeLayout/android.support.v7.widget.RecyclerView/android.widget.LinearLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout"
chat_head_cir="com.immuxin.muxin:id/chat_head_cir"
clear_message="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout[6]"
tvClear="com.immuxin.muxin:id/tvClear"
back="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout[1]/android.widget.ImageView"
right_is_read="com.immuxin.muxin:id/right_is_read"
ivPhoto="com.immuxin.muxin:id/ivPhoto"
photo="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[1]/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.LinearLayout/android.support.v7.widget.RecyclerView/android.view.View[1]/android.widget.TextView"
rightMessage_image="com.immuxin.muxin:id/rightMessage_image"
checkBox="com.immuxin.muxin:id/checkBox"
tv_done="com.immuxin.muxin:id/tv_done"
chat_head_lock="com.immuxin.muxin:id/chat_head_lock"
linear_pass="com.immuxin.muxin:id/linear_pass"
chat_head_secretly="com.immuxin.muxin:id/chat_head_secretly"
chat_secretly_image="com.immuxin.muxin:id/chat_secretly_image"
iv_back="com.immuxin.muxin:id/iv_back"
user_information="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout[4]"
friendmsg_userinfo_layout="com.immuxin.muxin:id/friendmsg_userinfo_layout"
ivMoreMenuItem="com.immuxin.muxin:id/ivMoreMenuItem"
location="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[3]/android.widget.LinearLayout/android.widget.GridView/android.widget.LinearLayout[3]/android.widget.ImageView"
location_information="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.RelativeLayout/android.widget.LinearLayout"
location_send="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout[3]/android.widget.TextView"
message_map="com.immuxin.muxin:id/message_map"
header_add_contasts="com.immuxin.muxin:id/header_add_contasts"
find_friends="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]"
friends_nearby="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout[3]"
fragment_contacts_mygroup="com.immuxin.muxin:id/fragment_contacts_mygroup"
red_bag="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[3]/android.widget.LinearLayout/android.widget.GridView/android.widget.LinearLayout[5]/android.widget.ImageView"
red_packets_money="com.immuxin.muxin:id/red_packets_money"
red_packets_button="com.immuxin.muxin:id/red_packets_button"
transfer_money_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.RelativeLayout[3]/android.widget.LinearLayout/android.widget.GridView/android.widget.LinearLayout[6]/android.widget.ImageView"
transfer_money="com.immuxin.muxin:id/transfer_money"
transfer_uniteButton="com.immuxin.muxin:id/transfer_uniteButton"




"个人中心"
et_UserName="com.immuxin.muxin:id/et_UserName"
et_Password="com.immuxin.muxin:id/et_Password"
loginBtn="com.immuxin.muxin:id/loginBtn"
account_pwd_login="com.immuxin.muxin:id/switch_account_pwd_login"
ll_me="com.immuxin.muxin:id/ll_me"
me_life_wallet_layout="com.immuxin.muxin:id/me_life_wallet_layout"
fragment_me_union_order="com.immuxin.muxin:id/fragment_me_union_order"
fragment_me_union_layout="com.immuxin.muxin:id/fragment_me_union_layout"
fragment_me_collection_layout="com.immuxin.muxin:id/fragment_me_collection_layout"
fragment_me_setup_layout="com.immuxin.muxin:id/fragment_me_setup_layout"
wallet_money2="com.immuxin.muxin:id/wallet_money2"
wallet_mudou="com.immuxin.muxin:id/wallet_mudou"
add_bank="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[1]/android.widget.LinearLayout/android.widget.LinearLayout[3]/android.widget.TextView"
bank_card="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout[2]/android.widget.TextView"
back_card_number="com.immuxin.muxin:id/back_card_number"
back_nex_step="com.immuxin.muxin:id/back_nex_step"